services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: hello
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  postgres_data: