# Generated by Django 5.0.6 on 2024-09-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_music', '0004_alter_contactmessage_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=108)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
